repos:
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v19.1.3
      hooks:
          - id: clang-format
            types_or: [c++]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0
      hooks:
          - id: prettier
            args: ["--tab-width=4"]
            files: "\\.(json|js|ts|css|md|yaml)$"
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.3.0
      hooks:
          - id: check-json
          - id: check-added-large-files
          - id: check-byte-order-marker
          - id: check-merge-conflict
            stages: [push]
          - id: debug-statements
            stages: [push]
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.6
      hooks:
          - id: forbid-tabs
            files: (.*\.py$)|(.*\.tmpl$)
